eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://discovery-service:8761/eureka
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: player-service
  config:
    import: optional:configserver:instead
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spellsofenglish_db
    username: postgres
    password: root

  flyway:
    locations: classpath:db/migration

server:
  port: 8070

management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans


