spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${G_CLIENT_ID}
            client-secret: ${G_CLIENT_SECRET}
            scope: openid,profile,email

  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: ${DRIVER_DB}
    url: ${URL_DB}
    username: ${LOGIN_DB}
    password: ${PASSWORD_DB}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host: ${HOST_MAIL}
    port: ${PORT_MAIL}
    username: ${LOGIN_MAIL}
server:
  port: 8080
  error:
    path: /error
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 10240
app:
  version: v1.0
  files:
    localStorage: files
  host: http://localhost:8080
  jwtSecret: testCode
  jwtExpirationMs: 86400000
  jwtCookieName: testName
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name:
    url:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  mail:
    host:
    port:
    username:
server:
  port: 8080
  error:
    path: /error
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 10240
app:
  host: http://000.000.000.000
