eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://discovery-service:8761/eureka
      defaultZone: http://127.0.0.1:8761/eureka
server:
  port: 8222

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:instead

  cloud:
    gateway:
      routes:
        - id: player-service
#          uri: http://player-service:8070
          uri: http://127.0.0.1:8070
          predicates:
            - Path=/api/v1/players/**
        - id: auth-service
          uri: http://127.0.0.1:8075
          predicates:
              - Path=/api/v1/auth/**
        - id: game-service
          uri: http://127.0.0.1:7550
          predicates:
              - Path=/api/v1/games/**

management:
  tracing:
    sampling:
      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
